development:
  adapter: postgresql
  encoding: utf8
  database: murarius_home_page_dev
  username: postgres
  password: <%= ENV["POSTGRES_PASS"] %>
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: murarius_home_page_test
  username: postgres
  password: <%= ENV["POSTGRES_PASS"] %>
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: murarius_home_page
  username: postgres
  password: <%= ENV["POSTGRES_PASS"] %>
  host: localhost
  port: 5432
